version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - CI=true npm test
  build:
    commands:
      - npm run-script build
      - rm -rf

artifacts:
  type: zip
  files:
    - build/*
  discard-paths: yes
